import { HttpPaths } from '@/Enums/httpPaths'
import { ILookups } from './_models'

const LookupsData: Array<ILookups> = [
  {
    addApi: HttpPaths.Api_Country_Upsert,
    deleteApi: HttpPaths.Api_Country_Delete,
    getApi: HttpPaths.Api_Country_GetAll,
    toggleApi: HttpPaths.Api_Country_ToggleIsActive,
    icon:"fa-solid fa-earth-africa",
    moduleName: 'Shared',
    routing: '/lookups/country',
    menuRouting: '/lookups/country',
    title: 'Country',
    columns: [{ field: 'name', header: 'Name' }],
    inputs: [
      {
        name: 'name',
        title: 'Name',
        value: null,
        isInput: true,
        isCheckBox: false,
        isDropDown: false,
        isMultiSelect: false,
        isTextArea: false,
        supplayDataURL: '',
        supplayData: [],
        isRequired: true,
        maxLength: 500,
        minLength: 1,
      },
    ],
    className: 'col-12',
    requireCompanyId: false,
  },
  {
    addApi: HttpPaths.Api_City_Upsert,
    deleteApi: HttpPaths.Api_City_Delete,
    getApi: HttpPaths.Api_City_GetAll,
    toggleApi: HttpPaths.Api_City_ToggleIsActive,
    icon:"fa-solid fa-city",
    moduleName: 'Shared',
    routing: '/lookups/city',
    menuRouting: '/lookups/city',
    title: 'City',
    columns: [{ field: 'name', header: 'Name' } , { field: 'countryName', header: 'Country Name' }],
    inputs: [
      {
        name: 'name',
        title: 'Name',
        value: null,
        isInput: true,
        isCheckBox: false,
        isDropDown: false,
        isMultiSelect: false,
        isTextArea: false,
        supplayDataURL: '',
        supplayData: [],
        isRequired: true,
        maxLength: 500,
        minLength: 1,
      },
      {
        name: 'country_Id',
        title: 'Country Name',
        value: null,
        isInput: false,
        isCheckBox: false,
        isDropDown: true,
        isMultiSelect: false,
        isTextArea: false,
        supplayDataURL: HttpPaths.Api_Country_ListOf,
        supplayData: [],
        isRequired: true,
        maxLength: 500,
        minLength: 1,
      },
    ],
    className: 'col-12',
    requireCompanyId: false,
  },
]

export default LookupsData
