import { HttpPaths } from '@/Enums/httpPaths';
import { ILookups } from './_models';

const LookupsData: Array<ILookups> = [

  {
    addApi: HttpPaths.Api_LeavesTypes_Upsert,
    deleteApi: HttpPaths.Api_LeavesTypes_Delete,
    getApi: HttpPaths.Api_LeavesTypes_GetAll,
    toggleApi: HttpPaths.Api_LeavesTypes_ToggleIsActive,
    moduleName: 'Leaves',
    routing: 'leave-type',
    menuRouting: 'leave-type',
    title: 'Leave Type',
    columns: [
      { field: 'name', header: 'Name' },
      { field: 'webColor', header: 'Web Color' },
      { field: 'mobileColor', header: 'Mobile Color' },
      {
        field: 'mustSubmittedBeforeDays',
        header: 'Submitted Before Days',
      },
      {
        field: 'leaveUnitInMinutes',
        header: 'Unit In Minutes',
        isBoolean: {
          value: true,
          iconTrue: 'check',
          iconFalse: 'x',
        },
      },
      {
        field: 'paid',
        header: 'Paid',
        isBoolean: {
          value: true,
          iconTrue: 'check',
          iconFalse: 'x',
        },
      },
    ],
    inputs: [
      {
        name: 'name',
        title: 'Name',
        value: null,
        isInput: true,
        isCheckBox: false,
        isDropDown: false,
        isMultiSelect: false,
        isTextArea: false,
        supplayDataURL: '',
        supplayData: [],
        isUrlRequireCompanyId: false,
        isRequired: true,
        maxLength: 500,
        minLength: 1,
      },
      {
        name: 'webColor',
        title: 'Web Color',
        value: null,
        isInput: true,
        isCheckBox: false,
        isDropDown: false,
        isMultiSelect: false,
        isTextArea: false,
        supplayDataURL: '',
        supplayData: [],
        isUrlRequireCompanyId: false,
        isRequired: true,
        maxLength: 500,
        minLength: 1,
      },
      {
        name: 'mobileColor',
        title: 'Mobile Color',
        value: null,
        isInput: true,
        isCheckBox: false,
        isDropDown: false,
        isMultiSelect: false,
        isTextArea: false,
        supplayDataURL: '',
        supplayData: [],
        isUrlRequireCompanyId: false,
        isRequired: true,
        maxLength: 500,
        minLength: 1,
      },
      {
        name: 'mustSubmittedBeforeDays',
        title: 'Submitted Before Days',
        value: null,
        isInput: true,
        isCheckBox: false,
        isDropDown: false,
        isMultiSelect: false,
        isTextArea: false,
        supplayDataURL: '',
        supplayData: [],
        isUrlRequireCompanyId: false,
        isRequired: true,
        maxLength: 500,
        minLength: 1,
      },
      {
        name: 'paid',
        title: 'Paid',
        value: null,
        isInput: false,
        isCheckBox: true,
        isDropDown: false,
        isMultiSelect: false,
        isTextArea: false,
        supplayDataURL: '',
        supplayData: [],
        isUrlRequireCompanyId: false,
        isRequired: false,
        maxLength: 500,
        minLength: 1,
      },
      {
        name: 'leaveUnitInMinutes',
        title: 'Unit In Minutes',
        value: null,
        isInput: false,
        isCheckBox: true,
        isDropDown: false,
        isMultiSelect: false,
        isTextArea: false,
        supplayDataURL: '',
        supplayData: [],
        isUrlRequireCompanyId: false,
        isRequired: false,
        maxLength: 500,
        minLength: 1,
      },
    ],
    className: 'col-12',
    requireCompanyId: false,
  },
];

export default LookupsData;
